FROM node:24 AS build

WORKDIR /app
COPY config/node/frontend/my-app/package.json .
RUN npm install

COPY config/node/frontend/my-app .

RUN npm run build



FROM nginx:alpine

COPY config/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]